### ISSUE TITLE
Is anchor free method only applicable to single class detection？

### ISSUE THREAD

**Issue by kaiopen** [tomztyang/3DSSD#12]
in `lib/np_functions/gt_sampler.py mask_assign_targets_anchors_np`:
```
if cls_num == 1: # anchor_free
    label_mask = np.ones([pts_num, cls_num], dtype=np.float32)
```

and in `lib/builder/anchor_builder.py`:
```
    def generate_anchors_free(self, points):
        """
        generate anchors based on points
        bs, npoint, 1, 3 -> bs, npoint, cls_num, 7
        """
        return tf.expand_dims(points, axis=2)
```
Do these mean if use anchor free, the number of classes is 1? And if the number of classes is larger than 1, the anchor-based method should be used?

**Comment by tomztyang** [comment]
Hi,
I haven't tested this code on multi-class circumstance. However, since in tensorflow or numpy, if a tensor with shape [bs, npoint, 1, 7] is added or multiplied with tensor as [bs, npoint, cls_num, 7], the output tensor has shape as [bs, npoint, cls_num, 7]. Therefore, the anchor-free generation method will not affect its utilization on multi-class circumstance.
