### ISSUE TITLE
problem for cyclist evaulation

### ISSUE THREAD

**Issue by FrankCAN** [tomztyang/3DSSD#15]
Hi, thanks for your impressive work, but when I run evaluator.py to evaluate cyclist class, the results are as below. But the car and pedestrian evaluations have no any problem, I don't understand why only the cyclist evaluation has the strange results. 

I also wonder if there is anyone who meet the similar problem, thanks.

Cyclist Evaluation:
precision_image:
[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00]
 [ 2.9914529e-04  3.1887757e-04  4.1296062e-04]
 [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00]]
precision_ground:
[[-1.0000000e+00 -1.0000000e+00 -1.0000000e+00]
 [ 1.2820514e-04  1.3192612e-04  1.3192612e-04]
 [-1.0000000e+00 -1.0000000e+00 -1.0000000e+00]]
precision_3d:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [-1. -1. -1.]]

Many thanks for your help.

**Comment by tomztyang** [comment]
Hi, 
Maybe the bug lies on the line 360 in kitti_dataloader.py. We only consider training with class [car] or classes [pedestrian, cyclist]. Therefore, in L360, if training model with [pedestrian, cyclist], all class index will be added by 1. If you wish to train class [cyclist] only, you have to add the class index by 2. 
Thank you so much for pointing this bug out.
